version: '3.7'

services:
  nginx:
    container_name: nginx
    environment:
      BUILD_ID: build_id
    build:
      dockerfile: Dockerfile.nginx
    networks:
      nginx_net:
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    ports:
      - 443:443
      - 80:80
  backend-node:
    container_name: backend
    networks:
      nginx_net:
    build:
      dockerfile: Dockerfile.backend
  certbot:
    container_name: certbot
    image: certbot/certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    networks:
      nginx_net:

networks:
  nginx_net:
    name: nginx_net
