stages:
  - dependencies
  - linters
  - build

default:
  image: node:22

.caches: &caches
  cache:
    key:
      files:
        - yarn.lock
    policy: pull
    paths:
      - node_modules

dependencies:
  cache:
    key:
      files:
        - yarn.lock
    paths:
      - node_modules
  stage: dependencies
  script:
    - yarn

linters:
  <<: *caches
  stage: linters
  needs: [dependencies]
  script:
    - yarn eslint
    - yarn stylelint
    - yarn prettier

build:
  <<: *caches
  needs: [dependencies]
  stage: build
  script:
    - yarn build
