name: build

on:
  push:
    branches: [master]

  pull_request:
    branches: [master]

jobs:
  dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 22
        uses: actions/setup-node@v4
        with:
          cache: "yarn"
          node-version: 22

      - name: Install dependencies
        run: yarn

  build:
    runs-on: ubuntu-latest
    needs: dependencies
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 22
        uses: actions/setup-node@v4
        with:
          cache: "yarn"
          node-version: 22

      - name: Install dependencies
        run: yarn

      - name: Build
        run: yarn run build

  linters:
    runs-on: ubuntu-latest
    needs: dependencies
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 22
        uses: actions/setup-node@v4
        with:
          cache: "yarn"
          node-version: 22

      - name: Install dependencies
        run: yarn

      - name: eslint
        run: yarn run eslint

      - name: eslint
        run: yarn run stylelint

      - name: eslint
        run: yarn run prettier
